# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git config user.email "jose.vera@alumnos.uv.cl"  
    git config user.name "jose"
    git checkout master
    git add --all
    git push https://$(gitToken)@github.com/JoseA-vn/HuntersLeaf. --force
  displayName: 'Github'
 